package api

import connectormgmt "github.com/aipermission/aipermission/backend/internal/gatewayconnectormanagement"

type createConnectorTargetRequest = connectormgmt.CreateTargetRequest

type createConnectorCredentialProfileRequest = connectormgmt.CredentialProfileInput

type updateConnectorTargetRequest = connectormgmt.UpdateTargetRequest

type updateConnectorCredentialProfileRequest = connectormgmt.CredentialProfileInput

type createConnectorTargetWithProfileRequest = connectormgmt.CreateTargetWithProfileRequest

type updateConnectorTargetWithProfileRequest = connectormgmt.UpdateTargetWithProfileRequest

type connectorTargetTestResponse = connectormgmt.ConnectionTestResponse

type connectorTargetResponse = connectormgmt.TargetResponse
type profileSummary = connectormgmt.ProfileSummary
type preparedConnectorCredentialProfileInput = connectormgmt.PreparedCredentialProfile
