package api

import "github.com/aipermission/aipermission/backend/internal/connectormanagement"

type createConnectorTargetRequest = connectormanagement.CreateTargetRequest

type createConnectorCredentialProfileRequest = connectormanagement.CredentialProfileInput

type updateConnectorTargetRequest = connectormanagement.UpdateTargetRequest

type updateConnectorCredentialProfileRequest = connectormanagement.CredentialProfileInput

type createConnectorTargetWithProfileRequest = connectormanagement.CreateTargetWithProfileRequest

type updateConnectorTargetWithProfileRequest = connectormanagement.UpdateTargetWithProfileRequest

type connectorTargetTestResponse = connectormanagement.ConnectionTestResponse

type connectorTargetResponse = connectormanagement.TargetResponse
type profileSummary = connectormanagement.ProfileSummary
type preparedConnectorCredentialProfileInput = connectormanagement.PreparedCredentialProfile
