// Code generated by backend/cmd/openapi. DO NOT EDIT.

export const connectorActionStatuses = Object.freeze([
  "completed",
  "failed",
  "canceled",
  "running",
  "approval_pending",
  "blocked",
  "stale",
  "declined",
  "error",
  "outcome_unknown",
] as const);

export const connectorRetryClasses = Object.freeze([
  "read_only",
  "idempotent",
  "conditional",
  "non_idempotent",
] as const);

export const executionRules = Object.freeze(["always_run", "approval_required", "blocked"] as const);

export const connectorActionResponseRequiredFields = Object.freeze([
  "status",
  "request_id",
  "target_ref",
  "connector_kind",
  "action_name",
  "retry_policy",
] as const);
