// Code generated by backend/cmd/openapi. DO NOT EDIT.

export declare const connectorActionStatuses: readonly [
  "completed",
  "failed",
  "canceled",
  "running",
  "approval_pending",
  "blocked",
  "stale",
  "declined",
  "error",
  "outcome_unknown",
];

export declare const connectorRetryClasses: readonly ["read_only", "idempotent", "conditional", "non_idempotent"];

export declare const executionRules: readonly ["always_run", "approval_required", "blocked"];

export declare const connectorActionResponseRequiredFields: readonly [
  "status",
  "request_id",
  "target_ref",
  "connector_kind",
  "action_name",
  "retry_policy",
];
