export const defaultProvisionForm = { role_name: "", profile_label: "", preset: "read_only" };

export const metadataSQL = `
SELECT
  n.nspname AS table_schema,
  c.relname AS table_name,
  COALESCE(
    json_agg(a.attname ORDER BY a.attnum) FILTER (WHERE a.attname IS NOT NULL),
    '[]'::json
  ) AS columns
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
WHERE c.relkind IN ('r', 'p', 'v', 'm', 'f')
  AND n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
GROUP BY n.nspname, c.relname
ORDER BY n.nspname, c.relname
`;

export function groupMetadataRows(rows) {
  const schemas = new Map();
  for (const row of rows || []) {
    const schemaName = String(row.table_schema || "").trim();
    const tableName = String(row.table_name || "").trim();
    const columns = metadataColumns(row);
    if (!schemaName || !tableName) continue;
    if (!schemas.has(schemaName)) schemas.set(schemaName, new Map());
    const tables = schemas.get(schemaName);
    if (!tables.has(tableName)) tables.set(tableName, []);
    if (columns.length > 0) tables.set(tableName, uniqueStrings([...tables.get(tableName), ...columns]));
  }
  return [...schemas.entries()].map(([name, tables]) => ({
    name,
    tables: [...tables.entries()].map(([tableName, columns]) => ({ name: tableName, columns })),
  }));
}

export function buildProvisionScope(scope) {
  if (scope.all_schemas) return { all_schemas: true };
  const schemas = Object.entries(scope.schemas || {})
    .filter(([, schema]) => schema.selected)
    .map(([schemaName, schema]) => {
      if (schema.all_tables) return { schema: schemaName, all_tables: true };
      const tables = Object.entries(schema.tables || {})
        .filter(([, table]) => table.selected)
        .map(([tableName, table]) => {
          if (table.all_columns) return { table: tableName, all_columns: true };
          return {
            table: tableName,
            all_columns: false,
            columns: Object.keys(table.columns || {}).filter((column) => table.columns[column]),
          };
        })
        .filter((table) => table.all_columns || table.columns.length > 0);
      return { schema: schemaName, all_tables: false, tables };
    })
    .filter((schema) => schema.all_tables || schema.tables.length > 0);
  return schemas.length === 0 ? null : { all_schemas: false, schemas };
}

export function toggleSchema(scope, schemaName, selected) {
  return updateScopeSchema(scope, schemaName, (current) => ({ ...current, selected, all_tables: current.all_tables ?? true }));
}

export function updateSchema(scope, schemaName, patch) {
  return updateScopeSchema(scope, schemaName, (current) => ({ ...current, ...patch }));
}

export function toggleTable(scope, schemaName, tableName, selected) {
  return updateScopeTable(scope, schemaName, tableName, (current) => ({ ...current, selected, all_columns: current.all_columns ?? true }));
}

export function updateTable(scope, schemaName, tableName, patch) {
  return updateScopeTable(scope, schemaName, tableName, (current) => ({ ...current, ...patch }));
}

export function toggleColumn(scope, schemaName, tableName, columnName, selected) {
  return updateScopeTable(scope, schemaName, tableName, (current) => ({
    ...current,
    columns: { ...(current.columns || {}), [columnName]: selected },
  }));
}

export function readableScopeSummary(scope, preset) {
  const privilege = preset === "read_write" ? "read and change rows" : "read rows";
  if (!scope) return "Choose at least one schema/table scope before creating the managed credential.";
  if (scope.all_schemas) {
    return `The generated role can ${privilege} across all non-system schemas visible to the admin profile.`;
  }
  const schemaCount = scope.schemas?.length || 0;
  const tableCount = (scope.schemas || []).reduce((sum, schema) => sum + (schema.all_tables ? 0 : schema.tables.length), 0);
  const allTableSchemas = (scope.schemas || []).filter((schema) => schema.all_tables).length;
  if (allTableSchemas === schemaCount) {
    return `The generated role can ${privilege} across all tables in ${schemaCount} selected schema${schemaCount === 1 ? "" : "s"}.`;
  }
  return `The generated role can ${privilege} on ${tableCount} selected table${tableCount === 1 ? "" : "s"} across ${schemaCount} schema${schemaCount === 1 ? "" : "s"}.`;
}

export function buildProvisionSQLPreview({ roleName, preset, database, scope }) {
  const role = quotePreviewIdentifier(cleanPreviewIdentifier(roleName) || "role_name");
  const cleanDatabase = cleanPreviewIdentifier(database) || "database";
  const privileges = preset === "read_write" ? "SELECT, INSERT, UPDATE, DELETE" : "SELECT";
  const lines = [
    `CREATE ROLE ${role} LOGIN PASSWORD '<random password generated by AIPermission>';`,
    `GRANT CONNECT ON DATABASE ${quotePreviewIdentifier(cleanDatabase)} TO ${role};`,
  ];
  if (!scope) {
    lines.push("-- Choose a scope to preview grants.");
    return lines.join("\n");
  }
  if (scope.all_schemas) {
    lines.push("-- For every non-system schema visible to the admin profile:");
    lines.push(`GRANT USAGE ON SCHEMA <schema> TO ${role};`);
    lines.push(`GRANT ${privileges} ON ALL TABLES IN SCHEMA <schema> TO ${role};`);
    return lines.join("\n");
  }
  appendScopedGrantPreview(lines, scope.schemas, role, privileges);
  return lines.join("\n");
}

export function safeBackupFilename(value) {
  const text = String(value || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return text || "postgres-backup";
}

function appendScopedGrantPreview(lines, schemas, role, privileges) {
  for (const schema of schemas || []) {
    const schemaSQL = quotePreviewIdentifier(schema.schema);
    lines.push(`GRANT USAGE ON SCHEMA ${schemaSQL} TO ${role};`);
    if (schema.all_tables) {
      lines.push(`GRANT ${privileges} ON ALL TABLES IN SCHEMA ${schemaSQL} TO ${role};`);
      continue;
    }
    for (const table of schema.tables || []) {
      const tableSQL = `${schemaSQL}.${quotePreviewIdentifier(table.table)}`;
      if (table.all_columns) {
        lines.push(`GRANT ${privileges} ON TABLE ${tableSQL} TO ${role};`);
      } else {
        const columns = (table.columns || []).map(quotePreviewIdentifier).join(", ");
        lines.push(`GRANT SELECT (${columns}) ON TABLE ${tableSQL} TO ${role};`);
      }
    }
  }
}

function metadataColumns(row) {
  if (Array.isArray(row.columns)) return row.columns.map(cleanColumn).filter(Boolean);
  if (typeof row.columns === "string" && row.columns.trim()) {
    try {
      const parsed = JSON.parse(row.columns);
      if (Array.isArray(parsed)) return parsed.map(cleanColumn).filter(Boolean);
    } catch {
      return row.columns.split(",").map(cleanColumn).filter(Boolean);
    }
  }
  const columnName = String(row.column_name || "").trim();
  return columnName ? [columnName] : [];
}

function cleanColumn(value) {
  return String(value || "").trim();
}

function uniqueStrings(items) {
  return [...new Set(items.filter(Boolean))];
}

function updateScopeSchema(scope, schemaName, updater) {
  const current = scope.schemas?.[schemaName] || { selected: false, all_tables: true, tables: {} };
  return { ...scope, schemas: { ...(scope.schemas || {}), [schemaName]: updater(current) } };
}

function updateScopeTable(scope, schemaName, tableName, updater) {
  return updateScopeSchema(scope, schemaName, (schema) => {
    const current = schema.tables?.[tableName] || { selected: false, all_columns: true, columns: {} };
    return { ...schema, tables: { ...(schema.tables || {}), [tableName]: updater(current) } };
  });
}

function cleanPreviewIdentifier(value) {
  const text = String(value || "").trim();
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(text) ? text : "";
}

function quotePreviewIdentifier(value) {
  return `"${String(value || "").replaceAll('"', '""')}"`;
}
