package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/aipermission/aipermission/backend/internal/connectors/builtin"
	"github.com/aipermission/aipermission/backend/internal/restcontract"
)

func main() {
	routesPath := flag.String("routes", "internal/api/httptransport/routes.go", "path to the Go route registration source")
	outputPath := flag.String("output", "../docs/api/openapi.json", "path to the generated OpenAPI document")
	frontendOutputPath := flag.String("frontend-output", "../frontend/src/lib/gateway-contracts/generated-connector-contract.js", "path to the generated frontend connector contract")
	check := flag.Bool("check", false, "verify that the generated document is current")
	flag.Parse()

	source, err := os.ReadFile(*routesPath)
	if err != nil {
		fatalf("read routes: %v", err)
	}
	output, err := generateContract(source)
	if err != nil {
		fatalf("%v", err)
	}
	if *check {
		verifyGeneratedFile(*outputPath, output)
		verifyGeneratedFile(*frontendOutputPath, generateFrontendContract())
		verifyGeneratedFile(frontendDeclarationPath(*frontendOutputPath), generateFrontendContractDeclaration())
		return
	}
	if err := os.WriteFile(*outputPath, output, 0o644); err != nil {
		fatalf("write generated contract: %v", err)
	}
	if err := os.WriteFile(*frontendOutputPath, generateFrontendContract(), 0o644); err != nil {
		fatalf("write generated frontend contract: %v", err)
	}
	if err := os.WriteFile(frontendDeclarationPath(*frontendOutputPath), generateFrontendContractDeclaration(), 0o644); err != nil {
		fatalf("write generated frontend contract declaration: %v", err)
	}
}

func frontendDeclarationPath(path string) string {
	return strings.TrimSuffix(path, filepath.Ext(path)) + ".d.ts"
}

func verifyGeneratedFile(path string, expected []byte) {
	current, err := os.ReadFile(path)
	if err != nil {
		fatalf("read generated contract %s: %v", path, err)
	}
	if !bytes.Equal(current, expected) {
		fatalf("%s is stale; run make rest-contract", path)
	}
}

func generateFrontendContract() []byte {
	var output strings.Builder
	output.WriteString("// Code generated by backend/cmd/openapi. DO NOT EDIT.\n\n")
	writeJavaScriptList(&output, "connectorActionStatuses", restcontract.ConnectorActionStatuses())
	output.WriteByte('\n')
	writeJavaScriptList(&output, "connectorRetryClasses", restcontract.ConnectorRetryClasses())
	output.WriteByte('\n')
	writeJavaScriptList(&output, "executionRules", restcontract.ConnectorExecutionRules())
	output.WriteByte('\n')
	writeJavaScriptList(&output, "connectorActionResponseRequiredFields", restcontract.ConnectorActionResponseRequiredFields())
	return []byte(output.String())
}

func generateFrontendContractDeclaration() []byte {
	var output strings.Builder
	output.WriteString("// Code generated by backend/cmd/openapi. DO NOT EDIT.\n\n")
	writeTypeScriptDeclaration(&output, "connectorActionStatuses", restcontract.ConnectorActionStatuses())
	output.WriteByte('\n')
	writeTypeScriptDeclaration(&output, "connectorRetryClasses", restcontract.ConnectorRetryClasses())
	output.WriteByte('\n')
	writeTypeScriptDeclaration(&output, "executionRules", restcontract.ConnectorExecutionRules())
	output.WriteByte('\n')
	writeTypeScriptDeclaration(&output, "connectorActionResponseRequiredFields", restcontract.ConnectorActionResponseRequiredFields())
	return []byte(output.String())
}

func writeJavaScriptList(output *strings.Builder, name string, values []string) {
	writeGeneratedList(output, fmt.Sprintf("export const %s = Object.freeze([", name), "]);", values)
}

func writeTypeScriptDeclaration(output *strings.Builder, name string, values []string) {
	writeGeneratedList(output, fmt.Sprintf("export declare const %s: readonly [", name), "];", values)
}

func writeGeneratedList(output *strings.Builder, prefix string, suffix string, values []string) {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	inline := prefix + strings.Join(quoted, ", ") + suffix
	if len(inline) <= 120 {
		output.WriteString(inline)
		output.WriteByte('\n')
		return
	}
	output.WriteString(prefix)
	output.WriteByte('\n')
	for _, value := range quoted {
		fmt.Fprintf(output, "  %s,\n", value)
	}
	output.WriteString(suffix)
	output.WriteByte('\n')
}

func generateContract(source []byte) ([]byte, error) {
	routes, err := restcontract.ParseRoutes(source)
	if err != nil {
		return nil, fmt.Errorf("parse core routes: %w", err)
	}
	catalog, err := builtin.NewCatalog()
	if err != nil {
		return nil, fmt.Errorf("load built-in connectors: %w", err)
	}
	connectorInfos := catalog.Connectors.List()
	kinds := make([]string, 0, len(connectorInfos))
	for _, info := range connectorInfos {
		kinds = append(kinds, info.Kind)
	}
	adapterRoutes, err := catalog.Adapters.RouteDefinitions(kinds)
	if err != nil {
		return nil, fmt.Errorf("load connector adapter routes: %w", err)
	}
	for _, route := range adapterRoutes {
		routes = append(routes, restcontract.Route{Method: route.Method, Path: route.Path})
	}
	output, err := restcontract.GenerateRoutes(routes)
	if err != nil {
		return nil, fmt.Errorf("generate contract: %w", err)
	}
	return output, nil
}

func fatalf(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", arguments...)
	os.Exit(1)
}
