package db

var coreTableStatements = []string{
	`CREATE TABLE IF NOT EXISTS connector_credential_resources (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		connector_kind TEXT NOT NULL,
		resource_kind TEXT NOT NULL,
		name TEXT NOT NULL,
		resource_type TEXT NOT NULL,
		public_data TEXT NOT NULL DEFAULT '',
		encrypted_secret TEXT NOT NULL DEFAULT '',
		fingerprint TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		UNIQUE(connector_kind, resource_kind, name)
	);`,
	`CREATE TABLE IF NOT EXISTS settings (
		key TEXT PRIMARY KEY,
		value TEXT NOT NULL,
		updated_at TEXT NOT NULL
	);`,
	`CREATE TABLE IF NOT EXISTS schema_migrations (
		version INTEGER PRIMARY KEY,
		description TEXT NOT NULL,
		applied_at TEXT NOT NULL
	);`,
	`CREATE TABLE IF NOT EXISTS api_tokens (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL UNIQUE,
		token_hash TEXT NOT NULL UNIQUE,
		token_prefix TEXT NOT NULL,
		token_value TEXT NOT NULL DEFAULT '',
		revoked_at TEXT,
		expires_at TEXT,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	);`,
	`CREATE TABLE IF NOT EXISTS connector_targets (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		connector_kind TEXT NOT NULL,
		name TEXT NOT NULL,
		config_json TEXT NOT NULL DEFAULT '{}',
		status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	);`,
	`CREATE TABLE IF NOT EXISTS connector_credential_profiles (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		target_id INTEGER NOT NULL,
		connector_kind TEXT NOT NULL,
		kind TEXT NOT NULL,
		label TEXT NOT NULL,
		public_json TEXT NOT NULL DEFAULT '{}',
		encrypted_secret_json TEXT NOT NULL DEFAULT '',
		risk_label TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		UNIQUE(id, target_id),
		FOREIGN KEY(target_id) REFERENCES connector_targets(id) ON DELETE RESTRICT
	);`,
	`CREATE TABLE IF NOT EXISTS connector_runtime_surfaces (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		connector_kind TEXT NOT NULL,
		target_id INTEGER NOT NULL,
		profile_id INTEGER NOT NULL,
		capability_kind TEXT NOT NULL,
		label TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		UNIQUE(connector_kind, target_id, profile_id, capability_kind),
		FOREIGN KEY(target_id) REFERENCES connector_targets(id) ON DELETE RESTRICT,
		FOREIGN KEY(profile_id, target_id) REFERENCES connector_credential_profiles(id, target_id) ON DELETE RESTRICT
	);`,
	`CREATE TABLE IF NOT EXISTS token_connector_action_permissions (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		token_id INTEGER NOT NULL,
		target_id INTEGER NOT NULL,
		profile_id INTEGER NOT NULL,
		action_name TEXT NOT NULL,
		execution_rule TEXT NOT NULL CHECK (execution_rule IN ('always_run', 'approval_required', 'blocked')),
		expires_at TEXT,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		UNIQUE(token_id, target_id, profile_id, action_name),
		FOREIGN KEY(token_id) REFERENCES api_tokens(id) ON DELETE CASCADE,
		FOREIGN KEY(target_id) REFERENCES connector_targets(id) ON DELETE RESTRICT,
		FOREIGN KEY(profile_id, target_id) REFERENCES connector_credential_profiles(id, target_id) ON DELETE RESTRICT
	);`,
	`CREATE TABLE IF NOT EXISTS command_requests (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		token_id INTEGER,
		runtime_id INTEGER NOT NULL,
		source TEXT NOT NULL DEFAULT 'mcp',
		command TEXT NOT NULL,
		encrypted_command TEXT NOT NULL DEFAULT '',
		reason TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL,
		stdout TEXT NOT NULL DEFAULT '',
		stderr TEXT NOT NULL DEFAULT '',
		exit_code INTEGER,
		session_id INTEGER,
			user_note TEXT,
			error TEXT NOT NULL DEFAULT '',
			tracking_reason TEXT NOT NULL DEFAULT '',
			output_truncated INTEGER NOT NULL DEFAULT 0,
			created_at TEXT NOT NULL,
			completed_at TEXT,
			FOREIGN KEY(token_id) REFERENCES api_tokens(id) ON DELETE SET NULL,
			FOREIGN KEY(runtime_id) REFERENCES connector_runtime_surfaces(id) ON DELETE RESTRICT
		);`,
	`CREATE TABLE IF NOT EXISTS bulk_command_idempotency (
		idempotency_key TEXT PRIMARY KEY,
		identity_hash TEXT NOT NULL,
		response_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		expires_at TEXT NOT NULL
	);`,
	`CREATE TABLE IF NOT EXISTS console_sessions (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		runtime_id INTEGER NOT NULL,
		name TEXT NOT NULL,
		status TEXT NOT NULL,
			transcript TEXT NOT NULL DEFAULT '',
			error TEXT NOT NULL DEFAULT '',
			cols INTEGER NOT NULL DEFAULT 120,
			rows INTEGER NOT NULL DEFAULT 32,
			created_at TEXT NOT NULL,
			updated_at TEXT NOT NULL,
			closed_at TEXT,
			FOREIGN KEY(runtime_id) REFERENCES connector_runtime_surfaces(id) ON DELETE RESTRICT
		);`,
	`CREATE TABLE IF NOT EXISTS console_session_chunks (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		session_id INTEGER NOT NULL,
		seq INTEGER NOT NULL,
		data TEXT NOT NULL,
		created_at TEXT NOT NULL,
		UNIQUE(session_id, seq),
		FOREIGN KEY(session_id) REFERENCES console_sessions(id) ON DELETE CASCADE
	);`,
	`CREATE TABLE IF NOT EXISTS message_queue (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		token_id INTEGER NOT NULL,
		runtime_id INTEGER,
			session_id INTEGER,
			direction TEXT NOT NULL DEFAULT 'user_to_ai',
			message TEXT NOT NULL,
			consumed_at TEXT,
			created_at TEXT NOT NULL,
			FOREIGN KEY(token_id) REFERENCES api_tokens(id) ON DELETE CASCADE,
			FOREIGN KEY(runtime_id) REFERENCES connector_runtime_surfaces(id) ON DELETE SET NULL,
			FOREIGN KEY(session_id) REFERENCES console_sessions(id) ON DELETE SET NULL
		);`,
	`CREATE TABLE IF NOT EXISTS connector_action_requests (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		token_id INTEGER,
		target_id INTEGER NOT NULL,
		profile_id INTEGER NOT NULL,
		connector_kind TEXT NOT NULL,
		action_name TEXT NOT NULL,
		title TEXT NOT NULL DEFAULT '',
		summary TEXT NOT NULL DEFAULT '',
		preview_json TEXT NOT NULL DEFAULT '{}',
		source TEXT NOT NULL DEFAULT 'mcp',
		input_json TEXT NOT NULL DEFAULT '{}',
		encrypted_payload_json TEXT NOT NULL DEFAULT '',
		reason TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL,
		output_json TEXT NOT NULL DEFAULT '{}',
		display_text TEXT NOT NULL DEFAULT '',
		error TEXT NOT NULL DEFAULT '',
		approval_context TEXT NOT NULL DEFAULT '',
		approval_context_hash TEXT NOT NULL DEFAULT '',
		approval_context_drift TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL,
		completed_at TEXT,
		FOREIGN KEY(token_id) REFERENCES api_tokens(id) ON DELETE SET NULL,
		FOREIGN KEY(target_id) REFERENCES connector_targets(id) ON DELETE RESTRICT,
		FOREIGN KEY(profile_id, target_id) REFERENCES connector_credential_profiles(id, target_id) ON DELETE RESTRICT
	);`,
	`CREATE TABLE IF NOT EXISTS audit_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		actor_type TEXT NOT NULL,
		token_id INTEGER,
		runtime_id INTEGER,
		connector_kind TEXT NOT NULL DEFAULT '',
		target_id INTEGER,
		profile_id INTEGER,
			action_request_id INTEGER,
			action TEXT NOT NULL,
			payload_json TEXT NOT NULL DEFAULT '{}',
			created_at TEXT NOT NULL,
			FOREIGN KEY(token_id) REFERENCES api_tokens(id) ON DELETE SET NULL,
			FOREIGN KEY(runtime_id) REFERENCES connector_runtime_surfaces(id) ON DELETE SET NULL
		);`,
	`CREATE TABLE IF NOT EXISTS redaction_rules (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			name TEXT NOT NULL UNIQUE,
			pattern TEXT NOT NULL,
			enabled INTEGER NOT NULL DEFAULT 1,
			created_at TEXT NOT NULL,
			updated_at TEXT NOT NULL
		);`,
	`CREATE TABLE IF NOT EXISTS history_labels (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL COLLATE NOCASE UNIQUE,
		color TEXT NOT NULL DEFAULT '#0f766e',
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	);`,
}

var fileTransferTableStatements = []string{
	`CREATE TABLE IF NOT EXISTS file_transfer_batches (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		runtime_id INTEGER NOT NULL,
		direction TEXT NOT NULL CHECK (direction IN ('upload', 'download')),
		source TEXT NOT NULL DEFAULT 'ui' CHECK (source IN ('ui', 'mcp')),
		status TEXT NOT NULL CHECK (status IN ('pending', 'pending_approval', 'running', 'paused', 'completed', 'failed', 'canceled')),
		archive_name TEXT NOT NULL DEFAULT '',
		approval_note TEXT NOT NULL DEFAULT '',
		overwrite INTEGER NOT NULL DEFAULT 0,
		archive_path TEXT NOT NULL DEFAULT '',
		total_items INTEGER NOT NULL DEFAULT 0,
		completed_items INTEGER NOT NULL DEFAULT 0,
		failed_items INTEGER NOT NULL DEFAULT 0,
		canceled_items INTEGER NOT NULL DEFAULT 0,
		size_bytes INTEGER NOT NULL DEFAULT 0,
			transferred_bytes INTEGER NOT NULL DEFAULT 0,
			bytes_per_second INTEGER NOT NULL DEFAULT 0,
			eta_seconds INTEGER NOT NULL DEFAULT -1,
			error TEXT NOT NULL DEFAULT '',
			created_at TEXT NOT NULL,
			started_at TEXT,
			completed_at TEXT,
			updated_at TEXT NOT NULL,
			FOREIGN KEY(runtime_id) REFERENCES connector_runtime_surfaces(id) ON DELETE RESTRICT
		);`,
	`CREATE TABLE IF NOT EXISTS file_transfers (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		batch_id INTEGER,
		queue_index INTEGER NOT NULL DEFAULT 0,
		runtime_id INTEGER NOT NULL,
		direction TEXT NOT NULL CHECK (direction IN ('upload', 'download')),
		source TEXT NOT NULL DEFAULT 'ui' CHECK (source IN ('ui', 'mcp')),
		status TEXT NOT NULL CHECK (status IN ('pending', 'pending_approval', 'running', 'paused', 'completed', 'failed', 'canceled')),
		local_path TEXT NOT NULL DEFAULT '',
		remote_path TEXT NOT NULL,
		file_name TEXT NOT NULL DEFAULT '',
		size_bytes INTEGER NOT NULL DEFAULT 0,
		transferred_bytes INTEGER NOT NULL DEFAULT 0,
		bytes_per_second INTEGER NOT NULL DEFAULT 0,
		eta_seconds INTEGER NOT NULL DEFAULT -1,
		checksum_sha256 TEXT NOT NULL DEFAULT '',
		temp_path TEXT NOT NULL DEFAULT '',
			error TEXT NOT NULL DEFAULT '',
			created_at TEXT NOT NULL,
			started_at TEXT,
			completed_at TEXT,
			updated_at TEXT NOT NULL,
			FOREIGN KEY(batch_id) REFERENCES file_transfer_batches(id) ON DELETE SET NULL,
			FOREIGN KEY(runtime_id) REFERENCES connector_runtime_surfaces(id) ON DELETE RESTRICT
		);`,
}

var historyTableStatements = []string{
	`CREATE TABLE IF NOT EXISTS history_entries (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		source_ref_type TEXT NOT NULL,
		source_ref_id INTEGER NOT NULL,
		connector_kind TEXT NOT NULL,
		activity_type TEXT NOT NULL,
		token_id INTEGER,
		runtime_id INTEGER,
		target_id INTEGER,
		profile_id INTEGER,
		target_name TEXT NOT NULL DEFAULT '',
		profile_label TEXT NOT NULL DEFAULT '',
		source TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL,
		action_name TEXT NOT NULL DEFAULT '',
		title TEXT NOT NULL DEFAULT '',
		summary TEXT NOT NULL DEFAULT '',
		preview_json TEXT NOT NULL DEFAULT '{}',
		input_text TEXT NOT NULL DEFAULT '',
		input_json TEXT NOT NULL DEFAULT '{}',
		output_text TEXT NOT NULL DEFAULT '',
		output_json TEXT NOT NULL DEFAULT '{}',
		error TEXT NOT NULL DEFAULT '',
		exit_code INTEGER,
		progress_current INTEGER NOT NULL DEFAULT 0,
		progress_total INTEGER NOT NULL DEFAULT 0,
		bytes_done INTEGER NOT NULL DEFAULT 0,
		bytes_total INTEGER NOT NULL DEFAULT 0,
		approval_required INTEGER NOT NULL DEFAULT 0,
			user_note TEXT NOT NULL DEFAULT '',
			created_at TEXT NOT NULL,
			started_at TEXT,
			completed_at TEXT,
			updated_at TEXT NOT NULL,
			UNIQUE(source_ref_type, source_ref_id),
			FOREIGN KEY(token_id) REFERENCES api_tokens(id) ON DELETE SET NULL,
			FOREIGN KEY(runtime_id) REFERENCES connector_runtime_surfaces(id) ON DELETE SET NULL,
			FOREIGN KEY(target_id) REFERENCES connector_targets(id) ON DELETE SET NULL,
			FOREIGN KEY(profile_id) REFERENCES connector_credential_profiles(id) ON DELETE SET NULL
		);`,
	`CREATE TABLE IF NOT EXISTS history_entry_labels (
		history_entry_id INTEGER NOT NULL,
		label_id INTEGER NOT NULL,
		created_at TEXT NOT NULL,
		PRIMARY KEY(history_entry_id, label_id),
		FOREIGN KEY(history_entry_id) REFERENCES history_entries(id) ON DELETE CASCADE,
		FOREIGN KEY(label_id) REFERENCES history_labels(id) ON DELETE CASCADE
	);`,
}

var backupProviderTableStatements = []string{
	`CREATE TABLE IF NOT EXISTS backup_providers (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		provider_type TEXT NOT NULL,
		name TEXT NOT NULL,
		status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled', 'archived')),
		public_json TEXT NOT NULL DEFAULT '{}',
		encrypted_secret_json TEXT NOT NULL DEFAULT '',
		last_checked_at TEXT,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		UNIQUE(provider_type, name)
	);`,
	`CREATE TABLE IF NOT EXISTS backup_records (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		provider_id INTEGER NOT NULL,
		database_id TEXT NOT NULL,
		database_name TEXT NOT NULL,
		provider_file_id TEXT NOT NULL,
		filename TEXT NOT NULL,
		source_machine TEXT NOT NULL DEFAULT '',
		size_bytes INTEGER NOT NULL DEFAULT 0,
		checksum_sha256 TEXT NOT NULL DEFAULT '',
		backup_created_at TEXT NOT NULL,
		uploaded_at TEXT NOT NULL,
		metadata_json TEXT NOT NULL DEFAULT '{}',
		deleted_at TEXT,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		UNIQUE(provider_id, provider_file_id),
		FOREIGN KEY(provider_id) REFERENCES backup_providers(id) ON DELETE CASCADE
	);`,
}

var projectVaultTableStatements = []string{
	`CREATE TABLE vault_items (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL,
		encrypted_value TEXT NOT NULL DEFAULT '',
		owner_project_id INTEGER NOT NULL,
		secret_type TEXT NOT NULL,
		value_mode TEXT NOT NULL DEFAULT 'text' CHECK (value_mode IN ('text')),
		value_version INTEGER NOT NULL DEFAULT 1,
		metadata_revision INTEGER NOT NULL DEFAULT 1,
		encryption_version INTEGER NOT NULL DEFAULT 1,
		provider TEXT NOT NULL DEFAULT '',
		environment TEXT NOT NULL DEFAULT '',
		description TEXT NOT NULL DEFAULT '',
		expires_at TEXT,
		expiry_warning_days INTEGER NOT NULL DEFAULT 14,
		last_value_replaced_at TEXT NOT NULL,
		last_used_at TEXT,
		usage_count INTEGER NOT NULL DEFAULT 0,
		source TEXT NOT NULL CHECK (source IN ('imported', 'generated')),
		generator_kind TEXT NOT NULL DEFAULT '',
		generator_parameters_json TEXT NOT NULL DEFAULT '{}',
		status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		FOREIGN KEY(owner_project_id) REFERENCES projects(id) ON DELETE RESTRICT
	);`,
	`CREATE UNIQUE INDEX idx_vault_items_active_name
		ON vault_items(name COLLATE NOCASE)
		WHERE status = 'active';`,
	`CREATE INDEX idx_vault_items_owner_status_name
		ON vault_items(owner_project_id, status, name COLLATE NOCASE);`,
	`CREATE INDEX idx_vault_items_expiry
		ON vault_items(status, expires_at);`,
	`CREATE TABLE vault_item_projects (
		vault_item_id INTEGER NOT NULL,
		project_id INTEGER NOT NULL,
		assignment_revision INTEGER NOT NULL DEFAULT 1,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY(vault_item_id, project_id),
		FOREIGN KEY(vault_item_id) REFERENCES vault_items(id) ON DELETE CASCADE,
		FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT
	);`,
	`CREATE INDEX idx_vault_item_projects_project
		ON vault_item_projects(project_id, vault_item_id);`,
	`CREATE TABLE vault_item_usage_notes (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		vault_item_id INTEGER NOT NULL,
		location TEXT NOT NULL,
		notes TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		FOREIGN KEY(vault_item_id) REFERENCES vault_items(id) ON DELETE CASCADE
	);`,
	`CREATE INDEX idx_vault_item_usage_notes_item
		ON vault_item_usage_notes(vault_item_id, id);`,
	`CREATE TABLE vault_item_tags (
		vault_item_id INTEGER NOT NULL,
		tag TEXT NOT NULL COLLATE NOCASE,
		created_at TEXT NOT NULL,
		PRIMARY KEY(vault_item_id, tag),
		FOREIGN KEY(vault_item_id) REFERENCES vault_items(id) ON DELETE CASCADE
	);`,
	`CREATE TABLE vault_default_bindings (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		vault_item_id INTEGER NOT NULL,
		source_project_id INTEGER NOT NULL,
		target_id INTEGER NOT NULL,
		profile_id INTEGER NOT NULL,
		replace_existing INTEGER NOT NULL DEFAULT 0 CHECK (replace_existing IN (0, 1)),
		binding_revision INTEGER NOT NULL DEFAULT 1,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		UNIQUE(vault_item_id, source_project_id, target_id, profile_id),
		FOREIGN KEY(vault_item_id) REFERENCES vault_items(id) ON DELETE CASCADE,
		FOREIGN KEY(source_project_id) REFERENCES projects(id) ON DELETE RESTRICT,
		FOREIGN KEY(target_id) REFERENCES connector_targets(id) ON DELETE RESTRICT,
		FOREIGN KEY(profile_id, target_id) REFERENCES connector_credential_profiles(id, target_id) ON DELETE RESTRICT
	);`,
	`CREATE INDEX idx_vault_default_bindings_profile
		ON vault_default_bindings(target_id, profile_id, vault_item_id);`,
	`CREATE TABLE token_project_capabilities (
		token_id INTEGER NOT NULL,
		project_id INTEGER NOT NULL,
		capability_name TEXT NOT NULL,
		execution_rule TEXT NOT NULL CHECK (execution_rule IN ('always_run', 'approval_required', 'blocked')),
		expires_at TEXT,
		revision INTEGER NOT NULL DEFAULT 1,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY(token_id, project_id, capability_name),
		FOREIGN KEY(token_id) REFERENCES api_tokens(id) ON DELETE CASCADE,
		FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
	);`,
	`CREATE TABLE token_project_capability_revisions (
		token_id INTEGER NOT NULL,
		project_id INTEGER NOT NULL,
		capability_name TEXT NOT NULL,
		revision INTEGER NOT NULL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY(token_id, project_id, capability_name),
		FOREIGN KEY(token_id) REFERENCES api_tokens(id) ON DELETE CASCADE,
		FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
	);`,
	`CREATE TABLE vault_action_requests (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		token_id INTEGER NOT NULL,
		project_id INTEGER NOT NULL,
		runtime_id INTEGER,
		action_name TEXT NOT NULL,
		source TEXT NOT NULL DEFAULT 'mcp',
		input_json TEXT NOT NULL DEFAULT '{}',
		reason TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL,
		approval_context_json TEXT NOT NULL DEFAULT '{}',
		approval_context_hash TEXT NOT NULL DEFAULT '',
		idempotency_key TEXT NOT NULL,
		error TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL,
		completed_at TEXT,
		updated_at TEXT NOT NULL,
		UNIQUE(token_id, idempotency_key),
		FOREIGN KEY(token_id) REFERENCES api_tokens(id) ON DELETE CASCADE,
		FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE RESTRICT,
		FOREIGN KEY(runtime_id) REFERENCES connector_runtime_surfaces(id) ON DELETE SET NULL
	);`,
	`CREATE INDEX idx_vault_action_requests_token_status_created
		ON vault_action_requests(token_id, status, created_at);`,
	`CREATE TABLE vault_session_leases (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		token_id INTEGER NOT NULL,
		runtime_id INTEGER NOT NULL,
		session_id INTEGER NOT NULL,
		session_generation INTEGER NOT NULL,
		approval_context_hash TEXT NOT NULL,
		status TEXT NOT NULL CHECK (status IN ('active', 'expired', 'revoked')),
		expires_at TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		UNIQUE(token_id, runtime_id, session_id, session_generation, approval_context_hash),
		FOREIGN KEY(token_id) REFERENCES api_tokens(id) ON DELETE CASCADE,
		FOREIGN KEY(runtime_id) REFERENCES connector_runtime_surfaces(id) ON DELETE CASCADE,
		FOREIGN KEY(session_id) REFERENCES console_sessions(id) ON DELETE CASCADE
	);`,
	`CREATE INDEX idx_vault_session_leases_active
		ON vault_session_leases(token_id, runtime_id, status, expires_at);`,
}
